from datamodel import Symbol


AMETHYSTS: Symbol = "AMETHYSTS"
STARFRUIT: Symbol = "STARFRUIT"
CHOCOLATE: Symbol = "CHOCOLATE"
STRAWBERRIES: Symbol = "STRAWBERRIES"
ROSES: Symbol = "ROSES"
GIFT_BASKET: Symbol = "GIFT_BASKET"
COCONUT: Symbol = "COCONUT"
COCONUT_COUPON: Symbol = "COCONUT_COUPON"

POSITION_LIMITS = {
    AMETHYSTS: 20,
    STARFRUIT: 20,
    CHOCOLATE: 250,
    STRAWBERRIES: 350,
    ROSES: 60,
    GIFT_BASKET: 60,
    COCONUT: 300,
    COCONUT_COUPON: 600,
}