from datamodel import Symbol


AMETHYSTS: Symbol = "AMETHYSTS"
STARFRUIT: Symbol = "STARFRUIT"
CHOCOLATE: Symbol = "CHOCOLATE"
STRAWBERRIES: Symbol = "STRAWBERRIES"
ROSES: Symbol = "ROSES"
GIFT_BASKET: Symbol = "GIFT_BASKET"

POSITION_LIMITS = {
    AMETHYSTS: 20,
    STARFRUIT: 20,
    CHOCOLATE: 250,
    STRAWBERRIES: 350,
    ROSES: 60,
    GIFT_BASKET: 60,
}